id: I3CFFFA6D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T23:29:03+00:00'
last_modified: '2022-06-07T15:13:58.330450+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22951
  title: ཧུ་མ་དང་ཧུ་མའི་སྒྲུང་རབས་ཆེན་མོའི་དཔྱད་གླེང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    28C5:
      image_group_id: I1KG23018
      title: ''
      total_pages: 232
      order: 1
      base_file: 28C5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
